import { Bible, Book, Verse, DailyVerse, DailyDevotional } from '../../src/types';
import { COMPREHENSIVE_DAILY_VERSES, getDeterministicDailyVerse } from '../../src/data/dailyVerses';

export { COMPREHENSIVE_DAILY_VERSES, getDeterministicDailyVerse };

export const PUBLIC_BIBLES: Bible[] = [
  {
    id: 'web',
    abbreviation: 'WEB',
    name: 'World English Bible',
    description: 'A modern, readable, public domain translation in modern American English.',
    language: { id: 'eng', name: 'English', nameLocal: 'English' },
    copyright: 'Public Domain',
    infoUrl: 'https://worldenglish.bible',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'kjv',
    abbreviation: 'KJV',
    name: 'King James Version',
    description: 'Classic 1611 English translation known for majestic poetic cadence.',
    language: { id: 'eng', name: 'English', nameLocal: 'English' },
    copyright: 'Public Domain',
    infoUrl: 'https://www.gutenberg.org/ebooks/10',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'asv',
    abbreviation: 'ASV',
    name: 'American Standard Version (1901)',
    description: 'Highly accurate and literal word-for-word translation rooted in historical biblical scholarship.',
    language: { id: 'eng', name: 'English', nameLocal: 'English' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'ylt',
    abbreviation: 'YLT',
    name: "Young's Literal Translation",
    description: 'Extremely literal translation following original Hebrew and Greek syntax and verbal tense strictly.',
    language: { id: 'eng', name: 'English', nameLocal: 'English' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'darby',
    abbreviation: 'DARBY',
    name: 'Darby Bible Translation',
    description: 'Rigorous English translation by J.N. Darby utilizing the earliest critical manuscripts.',
    language: { id: 'eng', name: 'English', nameLocal: 'English' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'rvr1909',
    abbreviation: 'RVR09',
    name: 'Reina-Valera 1909',
    description: 'Edición clásica castellana de las Sagradas Escrituras.',
    language: { id: 'spa', name: 'Spanish', nameLocal: 'Español' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'lsg1910',
    abbreviation: 'LSG',
    name: 'Louis Segond 1910',
    description: 'Traduction française classique et élégante des Saintes Écritures.',
    language: { id: 'fra', name: 'French', nameLocal: 'Français' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'luther',
    abbreviation: 'LUT',
    name: 'Luther Bibel (1545)',
    description: 'Die historische deutsche Übersetzung des Alten und Neuen Testaments von Martin Luther.',
    language: { id: 'deu', name: 'German', nameLocal: 'Deutsch' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'almeida',
    abbreviation: 'ARC',
    name: 'Almeida Revista e Corrigida',
    description: 'Tradução tradicional das Sagradas Escrituras em Português por João Ferreira de Almeida.',
    language: { id: 'por', name: 'Portuguese', nameLocal: 'Português' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'synodal',
    abbreviation: 'RST',
    name: 'Russian Synodal Translation',
    description: 'Авторизованный русский синодальный перевод Священного Писания.',
    language: { id: 'rus', name: 'Russian', nameLocal: 'Русский' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'cuv',
    abbreviation: 'CUV',
    name: 'Chinese Union Version (和合本)',
    description: 'Standard modern Chinese translation widely used across Chinese-speaking congregations globally.',
    language: { id: 'zho', name: 'Chinese', nameLocal: '中文 (繁體/簡體)' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'tagalog',
    abbreviation: 'ADB',
    name: 'Ang Dating Biblia (1905)',
    description: 'Klasikong salin ng Banal na Kasulatan sa wikang Tagalog.',
    language: { id: 'tgl', name: 'Tagalog', nameLocal: 'Tagalog / Filipino' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'yoruba',
    abbreviation: 'BM',
    name: 'Bíbélì Mímọ́ (Yorùbá)',
    description: 'Ìwé Mímọ́ Ọlọ́run ní èdè Yorùbá fún ìkàwé àti ìjọsìn.',
    language: { id: 'yor', name: 'Yoruba', nameLocal: 'Èdè Yorùbá' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'igbo',
    abbreviation: 'BN',
    name: 'Bible Nsọ (Igbo)',
    description: 'Akwụkwọ Nsọ nke Chineke n’asụsụ Igbo.',
    language: { id: 'ibo', name: 'Igbo', nameLocal: 'Asụsụ Igbo' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
  {
    id: 'hausa',
    abbreviation: 'LMT',
    name: 'Littafi Mai Tsarki (Hausa)',
    description: 'Littafi Mai Tsarki na Tsohon Alkawari da Sabon Alkawari da Harshen Hausa.',
    language: { id: 'hau', name: 'Hausa', nameLocal: 'Harshen Hausa' },
    copyright: 'Public Domain',
    isPublicDomain: true,
    provider: 'public_domain',
  },
];

export interface BookDef {
  id: string;
  abbr: string;
  name: string;
  nameLong: string;
  chaptersCount: number;
  testament: 'OT' | 'NT';
  order: number;
}

export const BIBLE_BOOKS: BookDef[] = [
  // Old Testament
  { id: 'GEN', abbr: 'Gen', name: 'Genesis', nameLong: 'The First Book of Moses, Called Genesis', chaptersCount: 50, testament: 'OT', order: 1 },
  { id: 'EXO', abbr: 'Exo', name: 'Exodus', nameLong: 'The Second Book of Moses, Called Exodus', chaptersCount: 40, testament: 'OT', order: 2 },
  { id: 'LEV', abbr: 'Lev', name: 'Leviticus', nameLong: 'The Third Book of Moses, Called Leviticus', chaptersCount: 27, testament: 'OT', order: 3 },
  { id: 'NUM', abbr: 'Num', name: 'Numbers', nameLong: 'The Fourth Book of Moses, Called Numbers', chaptersCount: 36, testament: 'OT', order: 4 },
  { id: 'DEU', abbr: 'Deu', name: 'Deuteronomy', nameLong: 'The Fifth Book of Moses, Called Deuteronomy', chaptersCount: 34, testament: 'OT', order: 5 },
  { id: 'JOSH', abbr: 'Josh', name: 'Joshua', nameLong: 'The Book of Joshua', chaptersCount: 24, testament: 'OT', order: 6 },
  { id: 'JUDG', abbr: 'Judg', name: 'Judges', nameLong: 'The Book of Judges', chaptersCount: 21, testament: 'OT', order: 7 },
  { id: 'RUTH', abbr: 'Ruth', name: 'Ruth', nameLong: 'The Book of Ruth', chaptersCount: 4, testament: 'OT', order: 8 },
  { id: '1SAM', abbr: '1Sam', name: '1 Samuel', nameLong: 'The First Book of Samuel', chaptersCount: 31, testament: 'OT', order: 9 },
  { id: '2SAM', abbr: '2Sam', name: '2 Samuel', nameLong: 'The Second Book of Samuel', chaptersCount: 24, testament: 'OT', order: 10 },
  { id: '1KINGS', abbr: '1Ki', name: '1 Kings', nameLong: 'The First Book of the Kings', chaptersCount: 22, testament: 'OT', order: 11 },
  { id: '2KINGS', abbr: '2Ki', name: '2 Kings', nameLong: 'The Second Book of the Kings', chaptersCount: 25, testament: 'OT', order: 12 },
  { id: '1CHRON', abbr: '1Chr', name: '1 Chronicles', nameLong: 'The First Book of the Chronicles', chaptersCount: 29, testament: 'OT', order: 13 },
  { id: '2CHRON', abbr: '2Chr', name: '2 Chronicles', nameLong: 'The Second Book of the Chronicles', chaptersCount: 36, testament: 'OT', order: 14 },
  { id: 'EZRA', abbr: 'Ezra', name: 'Ezra', nameLong: 'The Book of Ezra', chaptersCount: 10, testament: 'OT', order: 15 },
  { id: 'NEH', abbr: 'Neh', name: 'Nehemiah', nameLong: 'The Book of Nehemiah', chaptersCount: 13, testament: 'OT', order: 16 },
  { id: 'ESTH', abbr: 'Esth', name: 'Esther', nameLong: 'The Book of Esther', chaptersCount: 10, testament: 'OT', order: 17 },
  { id: 'JOB', abbr: 'Job', name: 'Job', nameLong: 'The Book of Job', chaptersCount: 42, testament: 'OT', order: 18 },
  { id: 'PSA', abbr: 'Psa', name: 'Psalms', nameLong: 'The Book of Psalms', chaptersCount: 150, testament: 'OT', order: 19 },
  { id: 'PROV', abbr: 'Prov', name: 'Proverbs', nameLong: 'The Proverbs', chaptersCount: 31, testament: 'OT', order: 20 },
  { id: 'ECCL', abbr: 'Eccl', name: 'Ecclesiastes', nameLong: 'Ecclesiastes or, The Preacher', chaptersCount: 12, testament: 'OT', order: 21 },
  { id: 'SONG', abbr: 'Song', name: 'Song of Solomon', nameLong: 'The Song of Solomon', chaptersCount: 8, testament: 'OT', order: 22 },
  { id: 'ISA', abbr: 'Isa', name: 'Isaiah', nameLong: 'The Book of the Prophet Isaiah', chaptersCount: 66, testament: 'OT', order: 23 },
  { id: 'JER', abbr: 'Jer', name: 'Jeremiah', nameLong: 'The Book of the Prophet Jeremiah', chaptersCount: 52, testament: 'OT', order: 24 },
  { id: 'LAM', abbr: 'Lam', name: 'Lamentations', nameLong: 'The Lamentations of Jeremiah', chaptersCount: 5, testament: 'OT', order: 25 },
  { id: 'EZEK', abbr: 'Ezek', name: 'Ezekiel', nameLong: 'The Book of the Prophet Ezekiel', chaptersCount: 48, testament: 'OT', order: 26 },
  { id: 'DAN', abbr: 'Dan', name: 'Daniel', nameLong: 'The Book of Daniel', chaptersCount: 12, testament: 'OT', order: 27 },
  { id: 'HOS', abbr: 'Hos', name: 'Hosea', nameLong: 'Hosea', chaptersCount: 14, testament: 'OT', order: 28 },
  { id: 'JOEL', abbr: 'Joel', name: 'Joel', nameLong: 'Joel', chaptersCount: 3, testament: 'OT', order: 29 },
  { id: 'AMOS', abbr: 'Amos', name: 'Amos', nameLong: 'Amos', chaptersCount: 9, testament: 'OT', order: 30 },
  { id: 'OBAD', abbr: 'Obad', name: 'Obadiah', nameLong: 'Obadiah', chaptersCount: 1, testament: 'OT', order: 31 },
  { id: 'JONAH', abbr: 'Jonah', name: 'Jonah', nameLong: 'Jonah', chaptersCount: 4, testament: 'OT', order: 32 },
  { id: 'MIC', abbr: 'Mic', name: 'Micah', nameLong: 'Micah', chaptersCount: 7, testament: 'OT', order: 33 },
  { id: 'NAH', abbr: 'Nah', name: 'Nahum', nameLong: 'Nahum', chaptersCount: 3, testament: 'OT', order: 34 },
  { id: 'HAB', abbr: 'Hab', name: 'Habakkuk', nameLong: 'Habakkuk', chaptersCount: 3, testament: 'OT', order: 35 },
  { id: 'ZEPH', abbr: 'Zeph', name: 'Zephaniah', nameLong: 'Zephaniah', chaptersCount: 3, testament: 'OT', order: 36 },
  { id: 'HAG', abbr: 'Hag', name: 'Haggai', nameLong: 'Haggai', chaptersCount: 2, testament: 'OT', order: 37 },
  { id: 'ZECH', abbr: 'Zech', name: 'Zechariah', nameLong: 'Zechariah', chaptersCount: 14, testament: 'OT', order: 38 },
  { id: 'MAL', abbr: 'Mal', name: 'Malachi', nameLong: 'Malachi', chaptersCount: 4, testament: 'OT', order: 39 },

  // New Testament
  { id: 'MAT', abbr: 'Matt', name: 'Matthew', nameLong: 'The Gospel According to St. Matthew', chaptersCount: 28, testament: 'NT', order: 40 },
  { id: 'MARK', abbr: 'Mark', name: 'Mark', nameLong: 'The Gospel According to St. Mark', chaptersCount: 16, testament: 'NT', order: 41 },
  { id: 'LUKE', abbr: 'Luke', name: 'Luke', nameLong: 'The Gospel According to St. Luke', chaptersCount: 24, testament: 'NT', order: 42 },
  { id: 'JOHN', abbr: 'John', name: 'John', nameLong: 'The Gospel According to St. John', chaptersCount: 21, testament: 'NT', order: 43 },
  { id: 'ACTS', abbr: 'Acts', name: 'Acts', nameLong: 'The Acts of the Apostles', chaptersCount: 28, testament: 'NT', order: 44 },
  { id: 'ROM', abbr: 'Rom', name: 'Romans', nameLong: 'The Epistle of Paul the Apostle to the Romans', chaptersCount: 16, testament: 'NT', order: 45 },
  { id: '1COR', abbr: '1Cor', name: '1 Corinthians', nameLong: 'The First Epistle of Paul the Apostle to the Corinthians', chaptersCount: 16, testament: 'NT', order: 46 },
  { id: '2COR', abbr: '2Cor', name: '2 Corinthians', nameLong: 'The Second Epistle of Paul the Apostle to the Corinthians', chaptersCount: 13, testament: 'NT', order: 47 },
  { id: 'GAL', abbr: 'Gal', name: 'Galatians', nameLong: 'The Epistle of Paul the Apostle to the Galatians', chaptersCount: 6, testament: 'NT', order: 48 },
  { id: 'EPH', abbr: 'Eph', name: 'Ephesians', nameLong: 'The Epistle of Paul the Apostle to the Ephesians', chaptersCount: 6, testament: 'NT', order: 49 },
  { id: 'PHIL', abbr: 'Phil', name: 'Philippians', nameLong: 'The Epistle of Paul the Apostle to the Philippians', chaptersCount: 4, testament: 'NT', order: 50 },
  { id: 'COL', abbr: 'Col', name: 'Colossians', nameLong: 'The Epistle of Paul the Apostle to the Colossians', chaptersCount: 4, testament: 'NT', order: 51 },
  { id: '1THESS', abbr: '1Thess', name: '1 Thessalonians', nameLong: 'The First Epistle of Paul the Apostle to the Thessalonians', chaptersCount: 5, testament: 'NT', order: 52 },
  { id: '2THESS', abbr: '2Thess', name: '2 Thessalonians', nameLong: 'The Second Epistle of Paul the Apostle to the Thessalonians', chaptersCount: 3, testament: 'NT', order: 53 },
  { id: '1TIM', abbr: '1Tim', name: '1 Timothy', nameLong: 'The First Epistle of Paul the Apostle to Timothy', chaptersCount: 6, testament: 'NT', order: 54 },
  { id: '2TIM', abbr: '2Tim', name: '2 Timothy', nameLong: 'The Second Epistle of Paul the Apostle to Timothy', chaptersCount: 4, testament: 'NT', order: 55 },
  { id: 'TITUS', abbr: 'Titus', name: 'Titus', nameLong: 'The Epistle of Paul to Titus', chaptersCount: 3, testament: 'NT', order: 56 },
  { id: 'PHILEM', abbr: 'Philem', name: 'Philemon', nameLong: 'The Epistle of Paul to Philemon', chaptersCount: 1, testament: 'NT', order: 57 },
  { id: 'HEB', abbr: 'Heb', name: 'Hebrews', nameLong: 'The Epistle of Paul the Apostle to the Hebrews', chaptersCount: 13, testament: 'NT', order: 58 },
  { id: 'JAS', abbr: 'Jas', name: 'James', nameLong: 'The General Epistle of James', chaptersCount: 5, testament: 'NT', order: 59 },
  { id: '1PET', abbr: '1Pet', name: '1 Peter', nameLong: 'The First Epistle General of Peter', chaptersCount: 5, testament: 'NT', order: 60 },
  { id: '2PET', abbr: '2Pet', name: '2 Peter', nameLong: 'The Second Epistle General of Peter', chaptersCount: 3, testament: 'NT', order: 61 },
  { id: '1JOHN', abbr: '1John', name: '1 John', nameLong: 'The First Epistle General of John', chaptersCount: 5, testament: 'NT', order: 62 },
  { id: '2JOHN', abbr: '2John', name: '2 John', nameLong: 'The Second Epistle General of John', chaptersCount: 1, testament: 'NT', order: 63 },
  { id: '3JOHN', abbr: '3John', name: '3 John', nameLong: 'The Third Epistle General of John', chaptersCount: 1, testament: 'NT', order: 64 },
  { id: 'JUDE', abbr: 'Jude', name: 'Jude', nameLong: 'The General Epistle of Jude', chaptersCount: 1, testament: 'NT', order: 65 },
  { id: 'REV', abbr: 'Rev', name: 'Revelation', nameLong: 'The Revelation of St. John the Divine', chaptersCount: 22, testament: 'NT', order: 66 },
];

// Curated full passage texts for key books and chapters
export const KNOWN_CHAPTER_VERSES: Record<string, Array<{ number: number; text: string }>> = {
  'GEN.1': [
    { number: 1, text: 'In the beginning God created the heavens and the earth.' },
    { number: 2, text: 'The earth was formless and empty. Darkness was on the surface of the deep and God’s Spirit was hovering over the surface of the waters.' },
    { number: 3, text: 'God said, "Let there be light," and there was light.' },
    { number: 4, text: 'God saw the light, and saw that it was good. God divided the light from the darkness.' },
    { number: 5, text: 'God called the light "day", and the darkness he called "night". There was evening and there was morning, one day.' },
    { number: 6, text: 'God said, "Let there be an expanse in the middle of the waters, and let it divide the waters from the waters."' },
    { number: 7, text: 'God made the expanse, and divided the waters which were under the expanse from the waters which were above the expanse; and it was so.' },
    { number: 8, text: 'God called the expanse "sky". There was evening and there was morning, a second day.' },
    { number: 9, text: 'God said, "Let the waters under the sky be gathered together to one place, and let the dry land appear;" and it was so.' },
    { number: 10, text: 'God called the dry land "earth", and the gathering together of the waters he called "seas". God saw that it was good.' },
    { number: 11, text: 'God said, "Let the earth yield grass, herbs yielding seed, and fruit trees bearing fruit after their kind, with their seed in it, on the earth;" and it was so.' },
    { number: 12, text: 'The earth yielded grass, herbs yielding seed after their kind, and trees bearing fruit, with their seed in it, after their kind; and God saw that it was good.' },
    { number: 13, text: 'There was evening and there was morning, a third day.' },
    { number: 14, text: 'God said, "Let there be lights in the expanse of the sky to divide the day from the night; and let them be for signs, and for seasons, and for days and years;' },
    { number: 15, text: 'and let them be for lights in the expanse of the sky to give light on the earth;" and it was so.' },
    { number: 16, text: 'God made the two great lights: the greater light to rule the day, and the lesser light to rule the night. He also made the stars.' },
    { number: 17, text: 'God set them in the expanse of the sky to give light to the earth,' },
    { number: 18, text: 'and to rule over the day and over the night, and to divide the light from the darkness. God saw that it was good.' },
    { number: 19, text: 'There was evening and there was morning, a fourth day.' },
    { number: 20, text: 'God said, "Let the waters abound with living creatures, and let birds fly above the earth in the open expanse of the sky."' },
    { number: 21, text: 'God created the large sea creatures, and every living creature that moves, with which the waters swarmed, after their kind, and every winged bird after its kind. God saw that it was good.' },
    { number: 22, text: 'God blessed them, saying, "Be fruitful, and multiply, and fill the waters in the seas, and let birds multiply on the earth."' },
    { number: 23, text: 'There was evening and there was morning, a fifth day.' },
    { number: 24, text: 'God said, "Let the earth produce living creatures after their kind, livestock, creeping things, and animals of the earth after their kind;" and it was so.' },
    { number: 25, text: 'God made the animals of the earth after their kind, and the livestock after their kind, and everything that creeps on the ground after its kind. God saw that it was good.' },
    { number: 26, text: 'God said, "Let’s make man in our image, after our likeness. Let them have dominion over the fish of the sea, and over the birds of the sky, and over the livestock, and over all the earth, and over every creeping thing that creeps on the earth."' },
    { number: 27, text: 'God created man in his own image. In God’s image he created him; male and female he created them.' },
    { number: 28, text: 'God blessed them. God said to them, "Be fruitful, and multiply, fill the earth, and subdue it. Have dominion over the fish of the sea, over the birds of the sky, and over every living thing that moves on the earth."' },
    { number: 29, text: 'God said, "Behold, I have given you every herb yielding seed, which is on the surface of all the earth, and every tree, which bears fruit yielding seed. It will be your food."' },
    { number: 30, text: 'To every animal of the earth, and to every bird of the sky, and to everything that creeps on the earth, in which there is life, I have given every green herb for food;" and it was so.' },
    { number: 31, text: 'God saw everything that he had made, and behold, it was very good. There was evening and there was morning, a sixth day.' },
  ],

  'PSA.23': [
    { number: 1, text: 'The LORD is my shepherd; I shall not want.' },
    { number: 2, text: 'He makes me lie down in green pastures. He leads me beside still waters.' },
    { number: 3, text: 'He restores my soul. He guides me in the paths of righteousness for his name’s sake.' },
    { number: 4, text: 'Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.' },
    { number: 5, text: 'You prepare a table before me in the presence of my enemies. You have anointed my head with oil. My cup runs over.' },
    { number: 6, text: 'Surely goodness and loving kindness shall follow me all the days of my life, and I will dwell in Yahweh’s house forever.' },
  ],

  'PSA.91': [
    { number: 1, text: 'He who dwells in the secret place of the Most High will rest in the shadow of the Almighty.' },
    { number: 2, text: 'I will say of Yahweh, "He is my refuge and my fortress; my God, in whom I trust."' },
    { number: 3, text: 'For he will deliver you from the snare of the fowler, and from the deadly pestilence.' },
    { number: 4, text: 'He will cover you with his feathers. Under his wings you will take refuge. His faithfulness is your shield and rampart.' },
    { number: 5, text: 'You shall not be afraid of the terror by night, nor of the arrow that flies by day;' },
    { number: 6, text: 'nor of the pestilence that walks in darkness, nor of the destruction that wastes at noonday.' },
    { number: 7, text: 'A thousand may fall at your side, and ten thousand at your right hand; but it will not come near you.' },
    { number: 8, text: 'You will only look with your eyes, and see the recompense of the wicked.' },
    { number: 9, text: 'Because you have made Yahweh your refuge, and the Most High your dwelling place,' },
    { number: 10, text: 'no evil shall happen to you, neither shall any plague come near your dwelling.' },
    { number: 11, text: 'For he will give his angels charge over you, to guard you in all your ways.' },
    { number: 12, text: 'They will bear you up in their hands, lest you dash your foot against a stone.' },
    { number: 13, text: 'You will tread on the lion and cobra. You will trample the young lion and the serpent underfoot.' },
    { number: 14, text: '"Because he has set his love on me, therefore I will deliver him. I will set him on high, because he has known my name.' },
    { number: 15, text: 'He will call on me, and I will answer him. I will be with him in trouble. I will deliver him, and honor him.' },
    { number: 16, text: 'I will satisfy him with long life, and show him my salvation."' },
  ],

  'PROV.3': [
    { number: 1, text: 'My son, don’t forget my teaching, but let your heart keep my commandments;' },
    { number: 2, text: 'for length of days, and years of life, and peace, will they add to you.' },
    { number: 3, text: 'Don’t let kindness and truth forsake you. Bind them around your neck. Write them on the tablet of your heart.' },
    { number: 4, text: 'So you will find favor and good understanding in the sight of God and man.' },
    { number: 5, text: 'Trust in the LORD with all your heart, and don’t lean on your own understanding.' },
    { number: 6, text: 'In all your ways acknowledge him, and he will make your paths straight.' },
    { number: 7, text: 'Don’t be wise in your own eyes. Fear Yahweh, and depart from evil.' },
    { number: 8, text: 'It will be health to your body, and nourishment to your bones.' },
    { number: 9, text: 'Honor Yahweh with your substance, and with the first fruits of all your increase:' },
    { number: 10, text: 'so your barns will be filled with plenty, and your vats will overflow with new wine.' },
  ],

  'JOHN.1': [
    { number: 1, text: 'In the beginning was the Word, and the Word was with God, and the Word was God.' },
    { number: 2, text: 'The same was in the beginning with God.' },
    { number: 3, text: 'All things were made through him. Without him, nothing was made that has been made.' },
    { number: 4, text: 'In him was life, and the life was the light of men.' },
    { number: 5, text: 'The light shines in the darkness, and the darkness hasn’t overcome it.' },
    { number: 6, text: 'There came a man sent from God, whose name was John.' },
    { number: 7, text: 'The same came as a witness, that he might testify about the light, that all might believe through him.' },
    { number: 8, text: 'He was not the light, but was sent that he might testify about the light.' },
    { number: 9, text: 'The true light that enlightens everyone was coming into the world.' },
    { number: 10, text: 'He was in the world, and the world was made through him, and the world didn’t recognize him.' },
    { number: 11, text: 'He came to his own, and those who were his own didn’t receive him.' },
    { number: 12, text: 'But as many as received him, to them he gave the right to become God’s children, to those who believe in his name:' },
    { number: 13, text: 'who were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.' },
    { number: 14, text: 'The Word became flesh, and lived among us. We saw his glory, such glory as of the one and only Son of the Father, full of grace and truth.' },
  ],

  'JOHN.3': [
    { number: 1, text: 'Now there was a man of the Pharisees named Nicodemus, a ruler of the Jews.' },
    { number: 2, text: 'The same came to him by night, and said to him, "Rabbi, we know that you are a teacher come from God, for no one can do these signs that you do, unless God is with him."' },
    { number: 3, text: 'Jesus answered him, "Most certainly I tell you, unless one is born anew, he can’t see the Kingdom of God."' },
    { number: 4, text: 'Nicodemus said to him, "How can a man be born when he is old? Can he enter a second time into his mother’s womb, and be born?"' },
    { number: 5, text: 'Jesus answered, "Most certainly I tell you, unless one is born of water and the Spirit, he can’t enter into the Kingdom of God."' },
    { number: 16, text: 'For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.' },
    { number: 17, text: 'For God didn’t send his Son into the world to judge the world, but that the world should be saved through him.' },
  ],

  'ROM.8': [
    { number: 1, text: 'There is therefore now no condemnation to those who are in Christ Jesus, who don’t walk according to the flesh, but according to the Spirit.' },
    { number: 28, text: 'We know that all things work together for good for those who love God, to those who are called according to his purpose.' },
    { number: 31, text: 'What then shall we say to these things? If God is for us, who can be against us?' },
    { number: 38, text: 'For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers,' },
    { number: 39, text: 'nor height, nor depth, nor any other created thing, will be able to separate us from God’s love, which is in Christ Jesus our Lord.' },
  ],

  '1COR.13': [
    { number: 1, text: 'If I speak with the tongues of men and of angels, but don’t have love, I have become sounding brass, or a clanging cymbal.' },
    { number: 4, text: 'Love is patient and is kind; love doesn’t envy; love doesn’t brag, is not proud,' },
    { number: 5, text: 'doesn’t behave itself inappropriately, doesn’t seek its own way, is not provoked, takes no account of evil;' },
    { number: 6, text: 'doesn’t rejoice in unrighteousness, but rejoices with the truth;' },
    { number: 7, text: 'bears all things, believes all things, hopes all things, and endures all things.' },
    { number: 13, text: 'But now faith, hope, and love remain—these three. The greatest of these is love.' },
  ],

  'PHIL.4': [
    { number: 4, text: 'Rejoice in the Lord always! Again I will say, Rejoice!' },
    { number: 6, text: 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.' },
    { number: 7, text: 'And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.' },
    { number: 13, text: 'I can do all things through Christ who strengthens me.' },
    { number: 19, text: 'My God will supply every need of yours according to his riches in glory in Christ Jesus.' },
  ]
};

export const DAILY_VERSES: DailyVerse[] = COMPREHENSIVE_DAILY_VERSES;

export const DAILY_DEVOTIONAL: DailyDevotional = {
  id: 'devotional-today',
  title: 'Walking in Quiet Confidence',
  author: 'Holy Bible+ Editorial',
  scripturalReference: 'Isaiah 30:15',
  keyVerseText: 'In quietness and in trust shall be your strength.',
  content: `In a world that demands constant noise, speed, and immediate responses, God invites us into a sanctuary of stillness. Real spiritual strength does not come from striving harder or shouting louder; it flows from an unshakeable trust in God's sovereign control.\n\nWhen we pause to read Scripture, we align our minds with eternal truth rather than temporary circumstances. Whatever mountain or uncertainty stands before you today, remember that the Almighty God is walking alongside you. Take a deep breath, hand over your anxieties, and step forward in His steady grace.`,
  prayer: 'Heavenly Father, quiet my heart today amid the noise of the world. Grant me the wisdom to listen for Your still, small voice and the courage to trust Your timing. Fill my mind with Your peace. In Jesus’ name, Amen.',
  date: new Date().toISOString().split('T')[0],
};
